


const userSchema = new mongoose.Schema({
  googleId: String,
  displayName: String,
  email: String,
  photo: String,
  hijos: [hijoSchema],
  padres: [padreSchema],
  invitados: [invitadoSchema],
  fechaRegistro: { type: Date, default: Date.now },
  pagos: Object,
  correoEntradas: Object,
  estado_pago: Object,
  jornadasFiesta: Object,
  entradas_enviadas: Boolean,
  notificacion_enviada: Boolean,
  fecha_notificacion: Date,
  fecha_envio_entradas: Date,
  correo_validado: Boolean,
  password: String,
  intentosFallidos: Number,
  bloqueadoHasta: Date,
  passwordHash: String,
  historial: [userHistorialSchema],
  entregas: [userDeliverySchema],
  historialEntradas: [userHistorialEntradasSchema],
  historialEmail: [userHistorialSchema],
});
