// Configurations

// Imports
const dotenv = require('dotenv');

// Load .env
dotenv.config({ path: './.env.local' });

// URL
const URL_API = process.env.REACT_APP_URL_API;
const URL_WEB = process.env.REACT_APP_URL_WEB;

// Oauth
const OAUTH_FACEBOOK_ID = process.env.REACT_APP_OAUTH_FACEBOOK_ID;
const OAUTH_GOOGLE_ID = process.env.REACT_APP_OAUTH_GOOGLE_ID;
const OAUTH_INSTAGRAM_ID = process.env.REACT_APP_OAUTH_INSTAGRAM_ID;
const OAUTH_LINKEDIN_ID = process.env.REACT_APP_OAUTH_LINKEDIN_ID;
const OAUTH_TWITTER_ID = process.env.REACT_APP_OAUTH_TWITTER_ID;
const OAUTH_REDDIT_ID = process.env.REACT_APP_OAUTH_REDDIT_ID;
const OAUTH_DISCORD_ID = process.env.REACT_APP_OAUTH_DISCORD_ID;
const OAUTH_ZOOM_ID = process.env.REACT_APP_OAUTH_ZOOM_ID;

const OAUTH_GITHUB_ID = process.env.REACT_APP_OAUTH_GITHUB_ID;
const OAUTH_GITLAB_ID = process.env.REACT_APP_OAUTH_GITLAB_ID;
const OAUTH_DIGITALOCEAN_ID = process.env.REACT_APP_OAUTH_DIGITALOCEAN_ID;
const OAUTH_BITBUCKET_ID = process.env.REACT_APP_OAUTH_BITBUCKET_ID;
const OAUTH_AZURE_ID = process.env.REACT_APP_OAUTH_AZURE_ID;
const OAUTH_AZURE_TENANT = process.env.REACT_APP_OAUTH_AZURE_TENANT;

const OAUTH_SPOTIFY_ID = process.env.REACT_APP_OAUTH_SPOTIFY_ID;
const OAUTH_SHOPIFY_ID = process.env.REACT_APP_OAUTH_SHOPIFY_ID;
const OAUTH_SHOPIFY_STORE = process.env.REACT_APP_OAUTH_SHOPIFY_STORE;

const DATABASE_YEAR_NAME = process.env.DATABASE_YEAR_NAME || '';

const FLOW_API_KEY = process.env.FLOW_API_KEY;
const FLOW_SECRET_KEY = process.env.FLOW_SECRET_KEY;

const LOCAL_PORT = process.env.LOCAL_PORT || 5001;

const API_KEY = process.env.API_KEY || '123456';

const URL_SERVER = process.env.URL_SERVER || '';

/// Database
const DB_USER = process.env.DB_USER;
const DB_PASSWORD = process.env.DB_PASSWORD;
const DB_URL = process.env.DB_URL;
const DB_MAIN_DATABASE_NAME = process.env.DB_MAIN_DATABASE_NAME;


/// Testing
const TEST_API_DELETE_APODERADO_EMAIL = process.env.TEST_API_DELETE_APODERADO_EMAIL || 'false';
const TEST_API_ENVIAR_CORREOS_PRUEBA = process.env.TEST_API_ENVIAR_CORREOS_PRUEBA || 'false';
const TEST_API_DESACTIVAR_ENTRADAS = process.env.TEST_API_DESACTIVAR_ENTRADAS || 'false';
const TEST_API_ANULAR_ENTRADAS = process.env.TEST_API_ANULAR_ENTRADAS || 'false';
const TEST_API_GENERAR_ENTRADAS_FAMILIA = process.env.TEST_API_GENERAR_ENTRADAS_FAMILIA || 'false';
const TEST_DATABASE_YEAR_NAME = process.env.TEST_DATABASE_YEAR_NAME || '';
const TEST_API_BORRAR_ENTRADAS = process.env.TEST_API_BORRAR_ENTRADAS || 'false';


// Exports
module.exports = {
  URL_API,
  URL_WEB,
  OAUTH_FACEBOOK_ID,
  OAUTH_GOOGLE_ID,
  OAUTH_INSTAGRAM_ID,
  OAUTH_LINKEDIN_ID,
  OAUTH_TWITTER_ID,
  OAUTH_REDDIT_ID,
  OAUTH_DISCORD_ID,
  OAUTH_ZOOM_ID,
  OAUTH_GITHUB_ID,
  OAUTH_GITLAB_ID,
  OAUTH_DIGITALOCEAN_ID,
  OAUTH_BITBUCKET_ID,
  OAUTH_AZURE_ID,
  OAUTH_AZURE_TENANT,
  OAUTH_SPOTIFY_ID,
  OAUTH_SHOPIFY_ID,
  OAUTH_SHOPIFY_STORE,
  DATABASE_YEAR_NAME,
  FLOW_API_KEY,
  FLOW_SECRET_KEY,
  LOCAL_PORT,
  API_KEY,
  URL_SERVER,
  DB_USER,
  DB_PASSWORD,
  DB_URL,
  DB_MAIN_DATABASE_NAME,
  TEST_API_DELETE_APODERADO_EMAIL,
  TEST_API_ENVIAR_CORREOS_PRUEBA,
  TEST_API_DESACTIVAR_ENTRADAS,
  TEST_API_ANULAR_ENTRADAS,
  TEST_API_GENERAR_ENTRADAS_FAMILIA,
  TEST_DATABASE_YEAR_NAME,
  TEST_API_BORRAR_ENTRADAS
};
